apiVersion: v1
kind: Service
metadata:
  name: {{ template "moloch.name" . }}-capture
  namespace: default
  labels:
    app: {{ template "moloch.name" . }}
    role: capture
spec:
  ports:
  - name: tcp-8005
    protocol: TCP
    port: 8005
    targetPort: 8005
  clusterIP: None
  selector:
    app: {{ template "moloch.name" . }}
    role: capture

